import {
  ALMONDMILK,
  COCONUTMILK,
  CREAM,
  HEAVY_CREAM,
  LINE_THE_CUP,
  LIQUID_SWEETENER,
  MILK_CREAMER,
  NON_FAT_MILK,
  OATMILK,
  SOYMILK,
  SWEETNER_PACKETS,
  VANILLA_SWEET_CREAM,
  WATER,
  WHOLE_MILK
} from './details/add-ins.model';
import { SIZE_OPTIONS } from './details/details.model';
import { EXPRESSO_ROAST_OPTIONS, RISTRETTO_LONG_SHOT } from './details/espresso-shot-options.model';
import { SAUCES, SYRUPS } from './details/flavors.model';
import {
  CARAMEL_DRIZZLE,
  CHOCOLATE_CREAM_COLD,
  CINNAMON_DOLCE_SPRINKLES,
  MOCHA_DRIZZLE,
  PUMPKIN_CREAM_COLD,
  PUMPKIN_SPICE,
  SALTED_CARAMEL_CREAM_COLD,
  SPICED_APPLE_DRIZZLE,
  VANILLA_SWEET_CREAM_COLD
} from './details/toppings.model';

export const DEFAULT_SIZE_OPTIONS_1 = [SIZE_OPTIONS.SHORT, SIZE_OPTIONS.TALL, SIZE_OPTIONS.GRANDE, SIZE_OPTIONS.VENTI];
export const DEFAULT_SYRUPS = [
  SYRUPS.APPLE_BROWN_SUGAR,
  SYRUPS.BROWN_SUGAR_SYRUP,
  SYRUPS.CARAMEL_SYRUP,
  SYRUPS.CINNAMON_DOLCE_SYRUP,
  SYRUPS.HAZELNUT_SYRUP,
  SYRUPS.PEPPERMINT_SYRUP,
  SYRUPS.RASPBERRY_SYRUP,
  SYRUPS.TOASTED_VANILLA_SYRUP,
  SYRUPS.TOFFEE_NUT_SYRUP,
  SYRUPS.VANILLA_SYRUP,
  SYRUPS.SUGAR_FREE_VANILLA_SYRUP
];
export const DEFAULT_SAUCES = [SAUCES.MOCHA_SAUCE, SAUCES.NEW_DARK_CARAMEL_SAUCE, SAUCES.PUMPKIN_SAUCE, SAUCES.WHITE_CHOCOLATE_MOCHA_SAUCE];
export const DEFAULT_CINNAMON_TOPPING = [
  CINNAMON_DOLCE_SPRINKLES.EXTRA,
  CINNAMON_DOLCE_SPRINKLES.LIGHT,
  CINNAMON_DOLCE_SPRINKLES.NO_CINNAMON,
  CINNAMON_DOLCE_SPRINKLES.CINNAMON
];
export const DEFAULT_PUMPKIN_TOPPING = [PUMPKIN_SPICE.EXTRA, PUMPKIN_SPICE.LIGHT, PUMPKIN_SPICE.NO_PUMPKIN, PUMPKIN_SPICE.PUMPKIN];
export const DEFAULT_CARAMEL_DRIZZLE = [CARAMEL_DRIZZLE.EXTRA, CARAMEL_DRIZZLE.LIGHT, CARAMEL_DRIZZLE.NO_CARAMEL, CARAMEL_DRIZZLE.CARAMEL];
export const DEFAULT_MOCHA_DRIZZLE = [MOCHA_DRIZZLE.EXTRA, MOCHA_DRIZZLE.LIGHT, MOCHA_DRIZZLE.NO_MOCHA, MOCHA_DRIZZLE.NO_MOCHA];
export const DEFAULT_SPICED_DRIZZLE = [
  SPICED_APPLE_DRIZZLE.EXTRA,
  SPICED_APPLE_DRIZZLE.LIGHT,
  SPICED_APPLE_DRIZZLE.NO_SPICED_APPLE,
  SPICED_APPLE_DRIZZLE.SPICED_APPLE
];
export const DEFAULT_CHOCOLATE_COLDFOAM = [
  CHOCOLATE_CREAM_COLD.EXTRA,
  CHOCOLATE_CREAM_COLD.LIGHT,
  CHOCOLATE_CREAM_COLD.NO_CHOCOLATE,
  CHOCOLATE_CREAM_COLD.CHOCOLATE,
  CHOCOLATE_CREAM_COLD.SUBSTITUTE
];
export const DEFAULT_PUMPKIN_COLDFOAM = [
  PUMPKIN_CREAM_COLD.EXTRA,
  PUMPKIN_CREAM_COLD.LIGHT,
  PUMPKIN_CREAM_COLD.NO_PUMPKIN,
  PUMPKIN_CREAM_COLD.PUMPKIN
];
export const DEFAULT_CARAMEL_COLDFOAM = [
  SALTED_CARAMEL_CREAM_COLD.EXTRA,
  SALTED_CARAMEL_CREAM_COLD.LIGHT,
  SALTED_CARAMEL_CREAM_COLD.NO_CARAMEL,
  SALTED_CARAMEL_CREAM_COLD.CARAMEL,
  SALTED_CARAMEL_CREAM_COLD.SUBSTITUTE
];
export const DEFAULT_VANILLA_COLDFOAM = [
  VANILLA_SWEET_CREAM_COLD.EXTRA,
  VANILLA_SWEET_CREAM_COLD.LIGHT,
  VANILLA_SWEET_CREAM_COLD.NO_VANILLA,
  VANILLA_SWEET_CREAM_COLD.SUBSTITUTE,
  VANILLA_SWEET_CREAM_COLD.VANILLA
];
export const DEFAULT_LINE_THE_CUP = [LINE_THE_CUP.CARAMEL, LINE_THE_CUP.MOCHA];
export const DEFAULT_MILK_CREAMER = [MILK_CREAMER.EXTRA, MILK_CREAMER.LIGHT, MILK_CREAMER.NO_SPLASH, MILK_CREAMER.SPLASH];
export const DEFAULT_ALMONDMILK_CREAMER = [ALMONDMILK.EXTRA, ALMONDMILK.LIGHT, ALMONDMILK.SPLASH];
export const DEFAULT_COCONUTMILK_CREAMER = [COCONUTMILK.EXTRA, COCONUTMILK.LIGHT, COCONUTMILK.NO_SPLASH, COCONUTMILK.SPLASH];
export const DEFAULT_CREAM_CREAMER = [CREAM.EXTRA, CREAM.LIGHT, CREAM.SPLASH];
export const DEFAULT_HEAVY_CREAM_CREAMER = [HEAVY_CREAM.EXTRA, HEAVY_CREAM.LIGHT, HEAVY_CREAM.SPLASH];
export const DEFAULT_NON_FAT_MILK_CREAMER = [NON_FAT_MILK.EXTRA, NON_FAT_MILK.LIGHT, NON_FAT_MILK.SPLASH];
export const DEFAULT_OAT_MILK_CREAMER = [OATMILK.EXTRA, OATMILK.LIGHT, OATMILK.NO_SPLASH, OATMILK.SPLASH, OATMILK.SUBSTITUTE];
export const DEFAULT_SOY_MILK_CREAMER = [SOYMILK.EXTRA, SOYMILK.LIGHT, SOYMILK.SPLASH];
export const DEFAULT_WHOLE_MILK_CREAMER = [WHOLE_MILK.EXTRA, WHOLE_MILK.LIGHT, WHOLE_MILK.SPLASH];
export const DEFAULT_VANILLA_CREAMER = [
  VANILLA_SWEET_CREAM.EXTRA,
  VANILLA_SWEET_CREAM.LIGHT,
  VANILLA_SWEET_CREAM.NO_SPLASH,
  VANILLA_SWEET_CREAM.SPLASH
];
export const DEFAULT_WATER = [WATER.EXTRA, WATER.LIGHT, WATER.NO_SPLASH, WATER.WATER];
export const DEFAULT_LIQUID_SWEETNER = [LIQUID_SWEETENER.CLASSIC_SYRUP, LIQUID_SWEETENER.HONEY_BLEND, LIQUID_SWEETENER.LIQUID_CANE_SUGAR];
export const DEFAULT_SWEETNER_PACKETS = [
  SWEETNER_PACKETS.SUGAR,
  SWEETNER_PACKETS.SUGAR_RAW,
  SWEETNER_PACKETS.HONEY,
  SWEETNER_PACKETS.SPLENDA,
  SWEETNER_PACKETS.STEVIA_RAW
];
export const DEFAULT_EXPRESSO_OPTIONS = [
  EXPRESSO_ROAST_OPTIONS.SIGNATURE,
  EXPRESSO_ROAST_OPTIONS.BLONDE,
  EXPRESSO_ROAST_OPTIONS.DECAF,
  EXPRESSO_ROAST_OPTIONS.THIRD_DECAF,
  EXPRESSO_ROAST_OPTIONS.HALF_DECAF,
  EXPRESSO_ROAST_OPTIONS.TWO_THIRD_DECAF
];

export const DEFAULT_RISTRETO_LONG_SHOT = [RISTRETTO_LONG_SHOT.LONG_SHOT, RISTRETTO_LONG_SHOT.RISTRETTO];
